spring:
  rabbitmq:
    host: 192.168.1.44
    port: 5672
    username: guest
    password: guest
    #none 禁用发布确认模式，默认值， correlated发布消息成功后会触发回调方法 simple 有点复杂
    publisher-confirm-type: correlated
    #发布退回
    publisher-returns: true
    connection-timeout: 1s #连接超时时间
    template:
      retry:
        enabled: true #开启重试机制
        max-attempts: 3 #最大重试次数
        initial-interval: 1000ms #重试间隔
        multiplier: 1.0 # 失败后的重试间隔倍数下次等待时间 = initial-interval * multiplier
