server:
  port: 8086
spring:
  application:
    name: map-scenic-spot
  profiles:
    active: dev
  config:
    import:
      - classpath:config/jpa.yml
      - classpath:config/rabbitmq.yml
      - classpath:config/dubbo.yml
  cloud:
    # nacos服务地址
    nacos:
      discovery:
        namespace: public
        server-addr: 192.168.1.14:8848
    compatibility-verifier:
      enabled: false
  cache:
    type: redis
  datasource:
    hikari:
      #客户端等待连接池连接的最大毫秒数
      connection-timeout: 30000
      #连接池中维护的最小空闲连接数
      minimum-idle: 4
      #最大池大小
      maximum-pool-size: 8
      #允许连接池在连接池中空闲的最长时间（毫秒）
      idle-timeout: 30000
      #池中连接关闭的最长生命周期（毫秒）
      max-lifetime: 45000
      #从池返回的连接的默认自动提交行为（默认为true）
      auto-commit: true
      #连接池的名称
      pool-name: SpringDataJPAHikariCP
logging:
  level:
    com.nmz.map: DEBUG
