server:
  port: 8080
spring:
  application:
    name: map-gateway
  cloud:
    compatibility-verifier:
      enabled: false
    # nacos服务地址
    nacos:
      discovery:
        namespace: public
        server-addr: 192.168.1.44:8848
    gateway:
      # 跨域
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedHeaders: "*"
            allowedOrigins: "*"
            allowedMethods:
              - GET
                POST
                DELETE
                PUT
                OPTION
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: auth_route
          uri: lb://map-auth-server
          predicates:
            - Path=/auth/**
        - id: todo_route
          uri: lb://map-todo
          predicates:
            - Path=/todo/**
        - id: review_route
          uri: lb://map-review
          predicates:
            - Path=/review/**
        - id: trip_route
          uri: lb://map-trip
          predicates:
            - Path=/trip/**