spring:
  config:
    import:
      - classpath:config/db.yml
      - classpath:config/redis.yml
      - classpath:config/elasticsearch.yml
      - classpath:config/rabbitmq.yml
      - classpath:config/dubbo.yml