spring:
  datasource:
    url: jdbc:p6spy:mysql://192.168.1.14:3306/map?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
